# mabo-radar


ALL: ;

build:
	pyinstaller --icon=favicon.ico heartbeat.py 
    
build1:
	pyinstaller --onefile heartbeat.py
    
mon:
	nodemon --exec "c:/python27/python.exe" mabozen/app.py


.PHONY: build